# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version=4.0.0-alpha.2
mod_name=Helpful Commands
mod_description=A feature-rich Minecraft mod that adds many useful commands. Improve server management and give your players more fun and possibilities, or optimize your singleplayer experience. Interactive, supports permissions, easy to configure.
mod_author=Expecticament
mod_id=helpful_commands
license=MIT
maven_group=com.expecticament.helpfulcommands
archives_name=helpful_commands
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,)

# Dependencies

# https://fabricmc.net/develop/
fabric_loader_version=0.18.0
fabric_api_version=0.139.5+1.21.11

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.11.0-beta

# https://luckperms.net/wiki/Developer-API
luckperms_version=5.4

# https://github.com/architectury/architectury-loom/releases
architectury_loom_version=1.13

# https://mvnrepository.com/artifact/architectury-plugin/architectury-plugin.gradle.plugin
architectury_plugin_version=3.4

# https://parchmentmc.org/docs/getting-started
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# https://mvnrepository.com/artifact/com.gradleup.shadow/shadow-gradle-plugin
gradleup_shadow_version=9.2.2