# Project
version=4.2.3
group=com.expecticament.helpfulcommands
java_version=25

# Common
minecraft_version=26.2
minecraft_version_range=[26.2,)
mod_name=Helpful Commands
mod_author=expecticament
mod_id=helpfulcommands
license=MIT
credits=
description=A feature-rich Minecraft mod that adds many useful commands. Improve server management and give your players more fun and possibilities, or optimize your singleplayer experience. Interactive, supports permissions, easy to configure.

# Build options
buildJavadocJar=false

# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# https://fabricmc.net/develop
fabric_version=0.160.0+26.2
fabric_loader_version=0.19.3

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.57
neoforge_loader_version_range=[4,)

# https://github.com/lucko/fabric-permissions-api/releases
fabric_permissions_api_version=0.7.0

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
