blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://helpfulcommands.expecticament.com
    about: Be sure to read the documentation first. You may find the answers there.
